"""reframe retry bookkeeping

Revision ID: 38854df2081c
Revises: 38e6880ca240
Create Date: 2026-09-30 22:03:23.453948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38854df2081c'
down_revision: Union[str, Sequence[str], None] = '38e6880ca240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reframe_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('reframe_attempted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reframe_attempted_at')
    op.drop_column('tasks', 'reframe_attempts')
    # ### end Alembic commands ###
